Referencing again the library wrapper
arduino/arduino-pro-content pull request #102
Opened 2021-04-21 15:22 UTC by marqdevx

2021-04-21 15:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino/arduino-pro-content?pullRequest=102) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino/arduino-pro-content?pullRequest=102) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino/arduino-pro-content?pullRequest=102) it.</sub>

2021-04-21 16:03 UTC, sebromero requested changes
I'd add a bit more details to that as suggested.

2021-04-21 16:03 UTC, sebromero commented on content/tutorials/portenta-h7/por-ard-gs/content.md
>  Let's program the Portenta with the classic blink example to check if the connection to the board works:
```suggestion
Let's program the Portenta with the classic blink example to check if the connection to the board works. There are two ways to do that:
```

2021-04-21 16:03 UTC, sebromero commented on content/tutorials/portenta-h7/por-ard-gs/content.md
> +-   In the classic Arduino IDE open the blink example by clicking the menu entry File->Examples->01.Basics->Blink (Small will be required).
```suggestion
-   In the classic Arduino IDE open the blink example by clicking the menu entry File->Examples->01.Basics->Blink. You need to swap LOW and HIGH pin values as the built-in LED on Portenta is turned on by pulling it LOW.
```

2021-04-21 16:03 UTC, sebromero commented on content/tutorials/portenta-h7/por-ard-gs/content.md
> +-   By downloading the 'Arduino_Pro_Tutorials' library and going to File->Examples->Arduino_Pro_Tutorials->Setting Up Portenta H7 For Arduino->Blink
```suggestion
-   By downloading the 'Arduino_Pro_Tutorials' library and opening the pre-made sketch under File->Examples->Arduino_Pro_Tutorials->Setting Up Portenta H7 For Arduino->Blink 
```

2021-04-22 11:06 UTC, sebromero commented
@marqdevx Can you sign the CLA please? Check the link above

2021-04-22 11:26 UTC, marqdevx reviewed
LGTM

2021-04-25 12:01 UTC, merged