Vs ard lora
arduino/arduino-pro-content pull request #66
Opened 2021-01-29 15:13 UTC by Lenardgeorge

For tutorials:
- [*] I double checked the wiring in the schematics/images
- [*] I exported the cover image without background
- [*] I used SVG format for pure vector images
- [*] I updated the metadata.json file of the tutorial
- [*] I updated the metadata.json file of the previous tutorial to contain the "next" link
- [*] I did a spell checking before requesting a review
- [*] I used title case for titles

2021-02-02 12:32 UTC, GDJose requested changes

2021-02-02 12:32 UTC, GDJose commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +The LoRa module on the Vision Shield can be accessed by using the [MKRWAN library](https://github.com/arduino-libraries/MKRWAN). This library provides all the APIS to communicate with LoRa and LoRaWA
```suggestion
The LoRa module on the Vision Shield can be accessed by using the [MKRWAN library](https://github.com/arduino-libraries/MKRWAN)( if you can't find it in your examples list, you can go to **tools > library manager** and type "MKRWAN library" to install it). This library provides all the APIS to communicate with LoRa and LoRaWAN networks and can be Installed from the library Manager. The first code you need to upload and run is from the **MKRWAN** library, and its name is _FirstConfiguration_.
```

2021-02-02 12:32 UTC, GDJose commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +Please, consider that in Australia the boards connect correctly to TTN gateways on AS923 frequencies; AU915 frequencies requires the selection of sub band 2, not yet implemented in the firmware.
```suggestion
**Note:** Consider that in Australia the boards connect correctly to TTN gateways on AS923 frequencies; AU915 frequencies requires the selection of sub band 2, not yet implemented in the firmware.
```

2021-02-02 12:32 UTC, GDJose commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +Once the sketch completes upload, open the Serial Monitor. The following details will show:
```suggestion
Once you have added to the sketch the frequency according to your country, you can upload it to the board. Then, once the upload is completed open the Serial Monitor. The following details will show:
```

2021-02-02 12:32 UTC, GDJose commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +Your module version is: ARD-078 1.1.9
```suggestion
Your module version is: ARD-078 1.2.0
```

2021-02-02 12:32 UTC, GDJose commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +Your device EUI is: a8xxxxxxxxxxxx0a
```suggestion
Your device EUI is: a8xxxxxxxxxxxxxx
```

2021-02-02 12:32 UTC, GDJose commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +Are you connecting via OTAA (1) or ABP (2)?
@Lenardgeorge @i-herrera should the user select 1? or 2? or do nothing?

2021-02-02 12:32 UTC, GDJose commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +![vs_ard_ttn_device_overview](assets/vs_ard_ttn_device_overview.png)
@Lenardgeorge in the screenshot the app ID and the device ID don't match with the above description on how to name the device neither the previous screenshots

2021-02-02 12:32 UTC, GDJose commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +
```suggestion
[note]
**Note:** In order to select the way in which the board is going to connect with TTN  (OTAA or ABP) we need to configure it on the TTN portal. We will see which option we should select in the following steps.
[/note]
```

2021-02-02 12:32 UTC, GDJose commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +* activation mode (that in this case is OTAA),
```suggestion
* activation mode (that, in this case, is OTAA as you can see in the screenshot above),
```

2021-02-02 12:32 UTC, GDJose commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +**Reviewed by:** Lenard George [18.03.2020]
```suggestion
**Reviewed by:** Jose Garcia [02.02.2021]
```

2021-02-02 16:08 UTC, lunnea commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +**Note :** Ensure that you are within range (10 Km) from an available Lora Gateway before you try this tutorial. Check availability on [The Things Network map](https://www.thethingsnetwork.org/map).
```suggestion
**Note :** Ensure that you are within range (10 Km) from an available LoRa Gateway before you try this tutorial. Check availability on [The Things Network map](https://www.thethingsnetwork.org/map).
```

2021-02-02 16:12 UTC, lunnea commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +The Vision Shield LoRa can be connected to the TTN and can transmit data to other devices connected to this network through a secure channel. This channel is nothing but an applicaiton on the TTN net
```suggestion
The Vision Shield LoRa can be connected to the TTN and can transmit data to other devices connected to this network through a secure channel. This channel is nothing but an applicaiton on the TTN network dedicated for your board. In this tutorial, you will be guided through a step-by-step process of setting up your Portenta board and the Vision Shield LoRa to communicate with a TTN application. As stated before, you need to check for the coverage of one of the TTN gateways before you continue following this guide.  
```

2021-02-02 16:14 UTC, lunnea commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +Start by pointing your browser to www.thethingsnetwork.org and use the Sign Up button to setup an account. Next, then fill all the required fields to complete a new registration (skip this step and s
```suggestion
Start by pointing your browser to www.thethingsnetwork.org and use the Sign Up button to setup an account. Next, then fill all the required fields to complete a new registration (if you already have a TTN account, skip this step and continue by signing in).
```

2021-02-02 16:16 UTC, lunnea commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +Once you have created an account with TTN, you need to create a TTN [application](https://www.thethingsnetwork.org/docs/applications/). An application provides a way to aggregate data from different
```suggestion
Once you have created an account with TTN, you need to create a TTN [application](https://www.thethingsnetwork.org/docs/applications/). This(?) application provides a way to aggregate data from different devices, and then use these data with other online / offline tools. Go to your [console](https://console.thethingsnetwork.org), and click on **Applications**
```

2021-02-03 09:54 UTC, lunnea commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +Before your Portenta H7 can start communicating with the TTN you need to [register](https://www.thethingsnetwork.org/docs/devices/registration.html) it with an application. Go back to the TTN portal
```suggestion
Before your Portenta H7 can start communicating with the TTN you need to [register](https://www.thethingsnetwork.org/docs/devices/registration.html) the board with an application. Go back to the TTN portal and scroll to **Devices** section on your Application dashboard, then click **Register Device**.
```

2021-02-03 10:04 UTC, lunnea commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +On the registration page that shows up we must fill in two fields. The first one is the **Device ID** which this must be lowercase and without spaces. Since the ID should be unique, so you can use  t
```suggestion
On the registration page, fill in **Device ID** and **EUI**. 
**Note**:  The Device ID must be lowercase and without spaces. The **EUI** should be copied from the Serial Monitor.```

2021-02-03 10:25 UTC, lunnea commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +Next, introduce the **APP EUI** and the **APP KEY** in the Serial Monitor in a similar manner. If everything has gone fine, you will see this message:
```suggestion
Next, introduce the **APP EUI** and the **APP KEY** in the Serial Monitor. If this process is done successfully, you will see this message:
```

2021-02-03 10:28 UTC, lunnea commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +If you have sent the message successfuly you have configured Portenta H7 and the Lora Vision Shield on the TTN. We have retrieved the device EUI, used it to register the device in the TTN console, an
```suggestion
If you recieve this message, you have managed to configure the Portenta H7 and the Lora Vision Shield on the TTN.
 We have retrieved the device EUI, used it to register the device in the TTN console, and programmed the board using the data provided by TTN. Now, we can send data over the LoRa® network which can be viewed from anywhere in the world (as long as we have an Internet connection and our device is in range from a TTN gateway).
```

2021-02-03 10:32 UTC, lunnea commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +## Troubleshooting
General thought: Is it possible to provide different use cases in the Troubleshooting sections that entails "normal" issues that users may encounter?

2021-02-03 10:35 UTC, lunnea commented on content/tutorials/portenta-h7/vs-ard-lora/content.md
> +**Reviewed by:** Lenard George [18.03.2020]
```suggestion
**Reviewed by:** Linnea Åkerberg [03.02.2021] + 

```

2021-02-03 10:35 UTC, lunnea reviewed
Proofreading 3/2 2021

2021-02-04 10:50 UTC, Lenardgeorge reviewed
All changes have been reviewed

2021-02-04 11:20 UTC, Lenardgeorge reviewed
All changes have been reviewed

2021-02-04 15:59 UTC, merged